### PR TITLE
Add autosuggestions module

### LINKED ISSUE #35: Add zsh-autosuggestions module
I like following zsh script which offers based on the zsh-history a possible completion candidate which can be accepted with `<ctrl-f>`.

https://github.com/tarruda/zsh-autosuggestions

It feels like advertised unobtrusive and fast.

What I like most about zim compared to the many other zsh frameworks, is its speed. So I do not want to suggest feature creep or new modules which slow zim down which would undermine the spirit of zim.
Any critical thoughts are welcome.

### PR DESCRIPTION
**Pull request by Tuurlijk**
Fixes #35 

Please follow Zim's [code style guidelines](https://github.com/Eriner/zim/wiki/Code-Style-Guide).

### CODE REVIEW

**Comment by luizdepra** [comment]
Nice. I was looking for this.

**Comment by Tuurlijk** [comment]
Changes have been reverted

**Comment by Tuurlijk** [comment]
Should I close this pr and post a 'clean' pr ?

**Comment by Eriner** [comment]
No, normally you'd just rebase the branch and "fix-up" the commits, but I can take care of that at merge time.

**Comment by ratheesh** [comment]
Any update on this?

**Pull request closed without merging**
