### PR TITLE
[pacman] don't call sudo on pacaur

### PR DESCRIPTION
**Pull request by Tmplt**
alike yaourt, pacaur also handles SUID itself.

### CODE REVIEW

**Comment by Eriner** [comment]
Thanks, I'll merge this when I get a chance (no internet for the next week or so).

**Comment by Tmplt** [comment]
Broken commit, apparently `sudo` will still be called on `pacaur`. I'm not able to figure out why.

**Comment by Eriner** [comment]
Hm, that's odd. The commit looks correct.

**Comment by sebastianst** [comment]
Please pull, the pacman aliases introduced by the pacman module won't work with pacaur otherwise. Thanks!

**Comment by Eriner** [comment]
@Tmplt is this still broken in your testing?

**Comment by Tmplt** [comment]
I just tried to remove everything from my zsh config to only include zim, but the issue remains. I still have the feeling something on my system causes this, and not zim itself. But if you can pull this into a test branch or something the like, maybe @sebastianst could try on his system?

**Comment by Eriner** [comment]
I mean, the code itself looks absolutely fine. @sebastianst if you clone his repo/merge this PR, does that fix the issue for you?

**Comment by sebastianst** [comment]
I just cloned Tmplt/master and it works as expected. Merge please :)

**Pull request closed without merging**
