### PR TITLE
Small additions to [git] module

### PR DESCRIPTION
**Pull request by hypnoglow**
Just one alias fix and 2 new aliases

### CODE REVIEW

**Comment by Eriner** [comment]
the `grc` alias was intentionally avoided to prevent clobbering http://www.unix.com/man-page/debian/1/grc/

**Comment by hypnoglow** [comment]
I would argue on this.

Should ZIM care about distro-specific and user-specific apps?
For example, "ghostscript" package in Archlinux provides `gs` command which runs ghostscript interpreter. But in ZIM `gs` is for `git stash`.

I think ZIM user should care about his naming conflicts, using e.g. `unalias gs` after sourcing ZIM in `.zshrc`.
Another option is to allow aliases longer than 3 symbols, e.g. `grco` for `git rebase --continue`. 

I thinks alias names should be self-explanatory, so I won't try to remember that `grr` is for "git restart rebasing" which is `git rebase --continue`.

Anyway, that's only my thoughts, I'm trying to explore the best solutions, so no offence :)
If you do not agree, I will revert my change and fix `README.md` instead.

**Comment by Eriner** [comment]
It would be nice to determine how many people actually have `grc` ([grcat](https://github.com/pengwynn/grc/blob/master/grcat)) in their path. I agree completely that `grc` would be a better alias.

**Comment by Eriner** [comment]
After giving it some thought, I'm going to merge this. If anyone has `grc` in their PATH, to access the original `grc` command, either:

- `unalias grc` in `.zshrc` after zim init
- use `\grc` to access the "default" (explicitly the unaliased version)

**Comment by Eriner** [comment]
@hypnoglow if you just change the `grc` alias in the Readme, I'll merge this. Thanks!

**Comment by hypnoglow** [comment]
The README is already saying that: "```grc``` continues the rebase after merge conflicts are resolved."

**Comment by Eriner** [comment]
oh, derp. thanks! I thought it didn't and needed to be changed. Makes sense why it's a "fix" now. I'll pull in a moment.

**Pull request closed without merging**
