### PR TITLE
Fix parse error with older zsh versions

### PR DESCRIPTION
**Pull request by lnicola**
Fix for issue #61.

### CODE REVIEW

**Comment by Eriner** [comment]
Yes, this should work. Before, I was just checking if the variable was set at all (uncommented). I'll PR this later this afternoon. Thanks!

**Comment by lnicola** [comment]
But that would be `[[ -n ${var} ]]`, right? The same thing works in newer `zsh` versions, so I think they've extended the syntax for conditionals.

**Comment by Eriner** [comment]
Testing wth just the variable causes a "true" if the variable is set at all (with newer versions of ZSH) and is cleaner than the `-n` syntax, imo. The proposed change works (with the "true" test).

I don't have an issue pulling this, though I would also suggest that you upgrade your version of Zsh if possible. Zsh v5.0.2 was released on Dec 21, 2012. Any compatibility fix for old versions of Zsh that requires a substatial code change (this PR does not) are likely to get a "Update your software, you're running an almost 4 year old shell" from me.

As I said before, I'll merge this later today. Thanks for submitting the PR!

**Comment by lnicola** [comment]
Oh, don't worry, and thanks for including the fix. I didn't realize my zsh version was so old. It's the one in CentOS 7. I only asked because I don't know much about zsh and I never seen that syntax before.

**Comment by Eriner** [comment]
I've merged this PR. Thanks again!

**Pull request closed without merging**
