### PR TITLE
Fix #70: Tab-completion is intermittently broken

### LINKED ISSUE #70: [prompt] magicmace: tab-completion screws up prompt some times
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: 8ac887e8e99a7d6d865fe433291729a3f879eaf2
- gist of .zimrc: https://gist.github.com/Tmplt/62fa02066dc28e6601cdd725c7624f2a
- Zsh version: `zsh 5.2 (x86_64-unknown-linux-gnu)`
- gist of .zshrc: https://github.com/Tmplt/dotfiles/blob/desktop/zsh/.zshrc
- $(uname -mosr): `Linux 4.6.4-1-zen x86_64 GNU/Linux`

Description
-----------
Some times, when using tab-complete for command arguments of flags, the prompt's layout is screwed up, as the image shows:
broken prompt
When removing characters, the new left-most location for the cursor is the incorrect:
very broken
Because it should be:
working

This can also be caused by writing long commands.

Steps to reproduce
------------------
1. Use the `magicmace` theme
2. Utilize tab-completion where it can be used or write a lengthy command.

Images or other information
---------------------------
* Does not occur every time.
* Clearing the command line with ^L works as intended; the cursor is placed in the correct position.

### PR DESCRIPTION
**Pull request by ericbn**
Moving the `add-zsh-hook precmd` up did the trick for me.

### CODE REVIEW

**Comment by Eriner** [comment]
@Tmplt: has this fixed your issue?

Thanks @ericbn!

**Comment by Tmplt** [comment]
It didn't, no.

**Comment by ericbn** [comment]
@Tmplt, do you have any specific and consistent reproducible scenario?

**Comment by Tmplt** [comment]
@ericbn I was fortunate to find an easily reproducible way today: open a small terminal and `cd` into a directory deep enough to fill half the terminal. In there, try using tab-completion on some command, e.g. `cd`.

**Comment by ericbn** [comment]
From what I could test, the offender was `print -P`, where `-P` does [prompt expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Prompt-Expansion).

I took the freedom to also change a few things: Move the `add-zsh-hook precmd` up, add `prompt_magicmace_` prefix to all function names, add `COLOR_` prefix to all color global variables, and move assignment to `PROMPT` to `prompt_magicmace_setup`.

@Tmplt, can you please check again with the updated commit changes?

**Comment by Tmplt** [comment]
@ericbn, that fixed it! Cheers.

**Comment by Eriner** [comment]
@ericbn @Tmplt Great, I'll merge this fix this evening. Thanks you two!

**Pull request closed without merging**
