### PR TITLE
Support for multipart 7z archives

### PR DESCRIPTION
**Pull request by djape**
Add support for unarchiving of multipart 7z archives.
Example:
`unarchive multipart.7z.001`

### CODE REVIEW

**Comment by ericbn** [comment]
LGTM. Could be done for `*.zip.001` too...

**Comment by Eriner** [comment]
and rar...

**Comment by djape** [comment]
@ericbn AFAIK`zip -s` creates `multipart.z0x, ...` and `multipart.zip`, but `unzip` does not support multipart archives yet (you have to concatenate files first). `7z` can split archives using different formats, so maybe `(*.7z|*.001) 7za x "${archive_name}"` should be used. What do you think?

**Comment by ericbn** [comment]
> so maybe `(*.7z|*.001) 7za x "${archive_name}"` should be used. What do you think?

Good point, @djape: the `*.001` archives are specific to 7zip. I agree you suggestion.

**Comment by djape** [comment]
Done.

**Pull request merged**
